import Link from 'next/link'
import { Zap, TrendingUp, Lightbulb, Code, DollarSign, Users, KanbanSquare } from 'lucide-react'
import { Header } from '@/components/header'

export default function HomePage() {
  const features = [
    {
      icon: TrendingUp,
      title: 'Market Validation',
      description: 'Get comprehensive scoring across 6 key metrics to validate your idea\'s market potential.',
    },
    {
      icon: Lightbulb,
      title: 'AI-Powered Insights',
      description: 'Receive actionable improvement suggestions generated by advanced AI analysis.',
    },
    {
      icon: Code,
      title: 'Tech Stack Recommendations',
      description: 'Get personalized technology recommendations tailored to your specific SaaS idea.',
    },
    {
      icon: DollarSign,
      title: 'Pricing Strategy',
      description: 'Discover optimal pricing models and tier structures for your target market.',
    },
    {
      icon: Users,
      title: 'User Flow Planning',
      description: 'Visualize the complete user journey from onboarding to conversion.',
    },
    {
      icon: KanbanSquare,
      title: 'Development Roadmap',
      description: 'Get actionable MVP tickets organized by priority and estimated effort.',
    },
  ]

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-primary-600 via-primary-700 to-purple-800 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              Validate Your SaaS Ideas 
              <span className="block text-primary-200">with AI-Powered Insights</span>
            </h1>
            <p className="text-xl md:text-2xl text-primary-100 mb-8 max-w-3xl mx-auto">
              Turn your SaaS concept into a comprehensive business plan with market validation, 
              technical recommendations, and actionable development roadmaps.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/generate"
                className="bg-white text-primary-600 px-8 py-4 rounded-lg font-semibold text-lg hover:bg-primary-50 transition-colors inline-flex items-center justify-center"
              >
                <Zap className="mr-2 h-5 w-5" />
                Generate SaaS Plan
              </Link>
              <Link
                href="/about"
                className="border border-primary-200 text-white px-8 py-4 rounded-lg font-semibold text-lg hover:bg-primary-700 transition-colors inline-flex items-center justify-center"
              >
                Learn More
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Everything You Need to Validate Your SaaS Idea
            </h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Our AI-powered platform provides comprehensive analysis and actionable insights 
              for entrepreneurs, founders, and developers.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon
              return (
                <div
                  key={index}
                  className="bg-gray-50 rounded-xl p-8 hover:shadow-lg transition-shadow card-hover"
                >
                  <div className="bg-primary-600 p-3 rounded-lg w-fit mb-4">
                    <Icon className="h-6 w-6 text-white" />
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-3">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 bg-gray-900 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to Validate Your SaaS Idea?
          </h2>
          <p className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto">
            Join thousands of entrepreneurs who have successfully validated and planned 
            their SaaS products with our AI-powered platform.
          </p>
          <Link
            href="/generate"
            className="bg-primary-600 text-white px-8 py-4 rounded-lg font-semibold text-lg hover:bg-primary-700 transition-colors inline-flex items-center"
          >
            <Zap className="mr-2 h-5 w-5" />
            Get Started Now
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-50 border-t">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="text-center">
            <div className="flex items-center justify-center space-x-2 mb-4">
              <div className="bg-primary-600 p-2 rounded-lg">
                <Zap className="h-6 w-6 text-white" />
              </div>
              <span className="text-xl font-bold text-gray-900">SaaS Validator</span>
            </div>
            <p className="text-gray-600">
              Empowering entrepreneurs with AI-driven SaaS validation and planning.
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
} 